name: 'facebook_ads_integration_tests'
version: '1.1.0'
profile: 'integration_tests'
config-version: 2

vars:
  facebook_ads_schema: facebook_ads_integration_tests
  facebook_ads_account_history_identifier: "facebook_ads_account_history_data"
  facebook_ads_ad_history_identifier: "facebook_ads_ad_history_data"
  facebook_ads_ad_set_history_identifier: "facebook_ads_ad_set_history_data"
  facebook_ads_basic_ad_identifier: "facebook_ads_basic_ad_data"
  facebook_ads_basic_ad_actions_identifier: "facebook_ads_basic_ad_actions_data"
  facebook_ads_basic_ad_action_values_identifier: "facebook_ads_basic_ad_action_values_data"
  facebook_ads_campaign_history_identifier: "facebook_ads_campaign_history_data"
  facebook_ads_creative_history_identifier: "facebook_ads_creative_history_data"
  facebook_ads_demographics_country_identifier: "facebook_ads_demographics_country_data"
  facebook_ads_demographics_country_actions_identifier: "facebook_ads_demographics_country_actions_data"
  facebook_ads_demographics_region_identifier: "facebook_ads_demographics_region_data"
  facebook_ads_demographics_region_actions_identifier: "facebook_ads_demographics_region_actions_data"

  # Comment IN docs generate
  # facebook_ads__using_demographics_country: true # @docs-include
  # facebook_ads__using_demographics_region: true # @docs-include

  # Comment OUT for docs generation
  facebook_ads__basic_ad_passthrough_metrics: # @docs-ignore
    - name: "reach" # @docs-ignore
    - name: inline_link_clicks # @docs-ignore
      alias: inline_clicks_aliased # @docs-ignore
  facebook_ads__basic_ad_actions_passthrough_metrics: # @docs-ignore
    - name: 'inline' # @docs-ignore
      alias: 'conversion_value_inline' # @docs-ignore
    - name: '_1_d_view' # @docs-ignore
  facebook_ads__basic_ad_action_values_passthrough_metrics: # @docs-ignore
    - name: '_7_d_click' # @docs-ignore
  facebook_ads__conversion_action_types: # @docs-ignore
    - name: lead # @docs-ignore
    - pattern: offsite_conversion% # @docs-ignore
    - name: onsite_conversion.purchase # @docs-ignore
      where_sql: source_relation != 'no_purchase_source' # @docs-ignore

models:
  +schema: "facebook_ads_{{ var('directed_schema','dev') }}"

seeds:
  +docs:
    show: false
  facebook_ads_integration_tests:
    +column_types:
      id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      account_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      campaign_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_set_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      ad_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      creative_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
      page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      template_page_link: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
      _fivetran_synced: "timestamp"
      updated_time: "timestamp"
    facebook_ads_basic_ad_actions_data:
      +column_types:
        value: "float"
        inline: "float"
        _1_d_view: "float"
        _7_d_click: "float"
    facebook_ads_demographics_country_actions_data:
      +column_types:
        value: "float"
    facebook_ads_demographics_region_actions_data:
      +column_types:
        value: "float"
    
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True